### ISSUE TITLE
Bug: Hands do not disappear when webcam image shows no hands

### ISSUE THREAD

**Issue by afogel** [UW-MAGIC-lab/hidden_village#1]
Right now, hands that are drawn on the screen do not disappear when hands disappear from the webcam image.

While originally by design, this needs to be fixed in a more elegant way. Ideally, we want to cached hand landmarks for 2-3 frames so that we can run pose recognition on the hands, but we want the hands to disappear after those frames elapse if the hands are still not in the webcam image.

**Comment by tyrrr110** [comment]
temporary fix: instead of using the React hook useSetState to memoize poseData and update poseData by merging newPoseData to prevPoseData, tried using setState to handle the issue.
